### ISSUE TITLE
Codes are blurred when the editor screen is enlarged

### ISSUE THREAD

**Issue by KugaiKento** [AkshaySG14/haystack-public#9] opened 2024-08-24 15:06 UTC
Codes are blurred when the editor screen is enlarged

**Comment by AkshaySG14** [comment] 2024-08-24 18:12
Thanks for the feedback! This is a duplicate of https://github.com/AkshaySG14/haystack-public/issues/4.

May I know your OS and whether you're using an external monitor?

**Comment by AkshaySG14** [comment] 2024-08-27 04:51
This should be fixed on the current version of Haystack on the website! Could you try it and let me know?

**Closed as completed** 2024-08-31 05:44 UTC
