### ISSUE TITLE
[BUG] Parts of the menu are interrupted and hidden.

### ISSUE THREAD

**Issue by TwentyXX** [AkshaySG14/haystack-public#27] opened 2024-09-10 02:16 UTC
![スクリーンショット 2024-09-10 110738](https://github.com/user-attachments/assets/3c16d114-d6a7-43e9-a361-67a1d3743279)
This is a File, Edit, ... The same is true for the other menus, with the top row of menus being difficult to see and click on.
Haystack Version: 0.16
VS Code Version: 1.90.0
Chromium: 122.0.6261.156
OS: {3 }   (Windows 11)

**Comment by TwentyXX** [comment] 2024-09-10 02:23
![スクリーンショット 2024-09-10 112218](https://github.com/user-attachments/assets/34cd40f9-40a1-4c37-bd98-0146f269496f)
PS: This is not only a problem with the top bar, it is also hidden by the sidebar.

**Comment by AkshaySG14** [comment] 2024-09-10 02:28
Semi-duplicate of https://github.com/AkshaySG14/haystack-public/issues/24. This is fixed and will deploy hopefully in a couple of hours.

**Comment by AkshaySG14** [comment] 2024-09-10 03:00
@TwentyXX please let me know if I can make it clearer. I made the fix, but we need to deploy the newest version of Haystack (0.17) to the website, which we haven't done yet!

**Comment by AkshaySG14** [comment] 2024-09-11 00:54
This should be fixed in the latest version on the website: 0.17! Please let me know if it is not.

**Closed as completed** 2024-09-11 03:54 UTC
